version: 1
runtime: python27
application: mobility-mate
api_version: 1
threadsafe: true

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest

handlers:
- url: /icons
  static_dir: icons
- url: /data
  static_dir: data
- url: /new
  script: new.app
- url: /add
  script: add.app
- url: /list
  script: list.app
- url: /.*
  script: main.app
